### ISSUE TITLE
deleting apps

### ISSUE THREAD

**Issue by eugene-eeo** [giantswarm/app-operator#1145]
hey, I think there's an issue with deleting Apps on the MC causing leftover Chart CRs on a WC.
what we found is that, say you have an app called `wc-trust-manager` on an MC:

```
$ kubectl get apps
NAME
...
wc-trust-manager
...
```

you will have the following Chart CR on the WC:

```
$ kubectl get charts
NAME
...
trust-manager
...
```

if you delete the app, the chart CR will remain on the WC even after the App CR is gone from the MC (i.e. finalizers removed). I think the problematic line is here:

https://github.com/giantswarm/app-operator/blob/v6.7.0/service/controller/app/resource/chart/desired.go#L54

if I'm understanding correctly (from tracing the log output)
at the point of deletion the `cr.Name` would be `wc-trust-manager`, and that gets passed to the `ApplyDeleteChange` of chart resource, which means it would try to delete `wc-trust-manager` Chart CR from the WC when really it needs to delete `trust-manager` instead. I think we need to strip out the `wc-` prefix from that name.

**Comment by ljakimczuk** [comment]
@eugene-eeo it took us quite some time, but it is finally fixed 🙇
